version: "3.7"

networks:
  nginx-proxy:
    external: true

services:
  nuxt-nginx:
    container_name: radio-switch-nuxt-nginx
    build:
      context: ../src
      dockerfile: Dockerfile
    networks:
      - nginx-proxy
      - default
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ${FRONTEND_HOSTNAME},www.${FRONTEND_HOSTNAME}
      LETSENCRYPT_HOST: ${FRONTEND_HOSTNAME},www.${FRONTEND_HOSTNAME}
    expose:
      - 80
    volumes:
      - ./docker-configs/nginx:/etc/nginx/conf.d/
